export const MEDIA_LIST = "MEDIA_LIST";
export const LOAD_SPINER = "LOAD_SPINER";
export const MEDIA_ITEM = "MEDIA_ITEM";
export const OPEN_POPUP = "OPEN_POPUP";
export const LIST_COLLECTION_SAVED = "LIST_COLLECTION_SAVED";
export const SAVE_SUCCESS_COLLECTION = "SAVE_SUCCESS_COLLECTION";


